# Generated by Django 3.0.8 on 2020-11-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201113_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='date_created',
            new_name='seller_date_created',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='email',
            new_name='seller_email',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='seller_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phone',
            new_name='seller_phone',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='profile_pic',
            new_name='seller_profile_pic',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='user',
            new_name='seller_user',
        ),
    ]
