# Generated by Django 3.0.8 on 2021-01-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dbvh7sfop/image/upload/v1609412216/media/kkhypdgpvhg2b7pjp27m.png', null=True, upload_to=''),
        ),
    ]
