# Generated by Django 3.0.8 on 2020-11-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201107_1120'),
        ('shop', '0010_usercart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
        migrations.AddField(
            model_name='orders',
            name='customershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
    ]
