# Generated by Django 3.0.8 on 2020-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_orders_customershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
