# Generated by Django 3.0.8 on 2020-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='customer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
