# Generated by Django 3.0.8 on 2020-11-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orderupdate_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
    ]
