# Generated by Django 3.0.8 on 2020-11-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_orders_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='customer',
        ),
    ]
