# Generated by Django 3.0.8 on 2020-11-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
