# Generated by Django 3.0.8 on 2020-11-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201113_2046'),
        ('shop', '0019_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(to='accounts.Seller'),
        ),
    ]
