# Generated by Django 3.0.8 on 2020-11-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201113_2046'),
        ('shop', '0025_orders_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Seller'),
        ),
    ]
