# Generated by Django 3.0.8 on 2020-11-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201113_2046'),
        ('shop', '0030_auto_20201118_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Seller'),
        ),
    ]
