# Generated by Django 3.0.8 on 2020-11-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201113_2046'),
        ('shop', '0032_auto_20201120_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Seller'),
        ),
    ]
