# Generated by Django 3.0.8 on 2020-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20201127_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_qr',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=''),
        ),
    ]
