# Generated by Django 3.0.8 on 2020-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_orders_order_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mode',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=200, null=True),
        ),
    ]
