# Generated by Django 3.0.8 on 2021-01-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210102_1255'),
        ('shop', '0040_auto_20201230_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_qr',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SellerProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(default=0)),
                ('product_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product')),
                ('seller_pc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Seller')),
            ],
        ),
    ]
