# Generated by Django 3.0.8 on 2021-01-02 15:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20210102_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_qr',
            field=cloudinary.models.CloudinaryField(default='default_profile.png', max_length=255, verbose_name='qrcode'),
        ),
        migrations.AlterField(
            model_name='sellerproductstock',
            name='product_pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product'),
        ),
    ]
