# Generated by Django 3.0.8 on 2021-01-02 20:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20210102_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_qr',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qrcode'),
        ),
    ]
