# Generated by Django 3.0.8 on 2021-01-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20210103_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_qr',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
    ]
