# Generated by Django 3.0.8 on 2021-01-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20210103_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_qr',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/order_qr'),
        ),
    ]
