# Generated by Django 3.0.8 on 2021-01-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20210103_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
