# Generated by Django 3.0.8 on 2021-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20210116_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
