# Generated by Django 3.0.8 on 2021-01-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_product_product_name_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name_long',
        ),
    ]
