# Generated by Django 3.0.8 on 2021-01-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_remove_product_product_name_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
