# Generated by Django 3.0.8 on 2021-01-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20210116_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.BigIntegerField(max_length=25),
        ),
    ]
